### ISSUE TITLE
Dark theme implementation

### ISSUE THREAD

**Issue by blyndusk** [thelittlewonder/gitstalk#19]
I really like this website, but I'm too used to dark theme. So I want to implement one here ! Do you think it's a good idea ?

**Comment by thelittlewonder** [comment]
Shipped in https://github.com/thelittlewonder/gitstalk/commit/7b8413eb7cdab0f567757756bd2992c6b57e8715 🌓

Thanks for suggesting!

**Comment by vladimyr** [comment]
However, theme setting isn't persisted which makes it annoying and forces you to go and switch to the dark mode after every single reload 😢

**Comment by thelittlewonder** [comment]
Ah, I see. As of now, ideally, the theme should automatically change according to your current time (dark during night and vice versa) or your MacOS theme preference.

I will take up this issue and use local storage to store the theme! Thanks for bringing it up!

**Comment by thelittlewonder** [comment]
Made the changes in #28 :)

**Comment by vladimyr** [comment]
Works like a charm 👍
