### ISSUE TITLE
Website stopped working

### ISSUE THREAD

**Issue by yakov116** [thelittlewonder/gitstalk#36]
As of this morning I get 3 errors 
```js
Uncaught SyntaxError: Unexpected token '<'
vendor.525faf29f7c191162095.js:1 Uncaught SyntaxError: Unexpected token '<'
app.59e7d9f5249e49109f94.js:formatted:1 Uncaught SyntaxError: Unexpected token '<'
```

The last preview works fine https://deploy-preview-28--gitstalk.netlify.app/

**Comment by thelittlewonder** [comment]
Thanks for raising the issue! Fixed a few things, should be up now.

Can you please confirm?

**Comment by yakov116** [comment]
Working great!! I use it daily thanks for this awesome tool!
